# Generated by Django 4.2.8 on 2023-12-11 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product", "0001_initial"),
        ("vendor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                (
                    "order_number",
                    models.CharField(max_length=255, verbose_name="Order Number"),
                ),
                ("date", models.DateTimeField(verbose_name="Date")),
                (
                    "vendor_name",
                    models.CharField(max_length=255, verbose_name="Vendor Name"),
                ),
                ("igst", models.FloatField(default=0.0, verbose_name="IGST")),
                ("sgst", models.FloatField(default=0.0, verbose_name="SGST")),
                (
                    "total_discount_percentage",
                    models.FloatField(default=0.0, verbose_name="Percentage"),
                ),
                (
                    "total_discount_price",
                    models.FloatField(default=0.0, verbose_name="Price"),
                ),
                ("total_price", models.FloatField(default=0.0, verbose_name="Price")),
                (
                    "vendor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vendors",
                        to="vendor.vendor",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="PurchaseOrderProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                (
                    "purchase_order_number",
                    models.CharField(
                        max_length=255, verbose_name="Purchase Order Number"
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=255, verbose_name="Product Name"),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="Quantity")),
                (
                    "discount_percentage",
                    models.FloatField(default=0.0, verbose_name="Percentage"),
                ),
                (
                    "discount_price",
                    models.FloatField(default=0.0, verbose_name="Price"),
                ),
                (
                    "total_product_price",
                    models.FloatField(default=0.0, verbose_name="Price"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="product.product",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_orders",
                        to="purchase_order.purchaseorder",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
