# Generated by Django 4.2.8 on 2023-12-16 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase_order", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 16, 11, 15, 38, 798954, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="purchaseorder", name="updated_at", field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="purchaseorderproduct",
            name="created_at",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="purchaseorderproduct",
            name="updated_at",
            field=models.DateTimeField(),
        ),
    ]
