# Generated by Django 4.2.8 on 2023-12-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase_order", "0002_alter_purchaseorder_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="purchaseorderproduct",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="purchaseorderproduct",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
