# Generated by Django 4.2.8 on 2023-12-16 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_full_name_alter_user_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 16, 11, 20, 53, 382899, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 16, 11, 20, 56, 287479, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
    ]
