# Generated by Django 4.2.8 on 2023-12-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("name", models.CharField(max_length=255, verbose_name="Product Name")),
                ("price", models.FloatField(default=0.0, verbose_name="Price")),
                (
                    "descreption",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="descreption",
                    ),
                ),
                ("is_ban", models.BooleanField(default=False)),
                (
                    "hazmat_type",
                    models.CharField(
                        choices=[("R", "Regular"), ("H", "Hazmat")],
                        default="R",
                        max_length=255,
                        verbose_name="Hazamt Type",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
